// this file is auto generated by program,do not edit
#include "RpcMethodHandler.h"
#include "RpcService.h"
#include "protocols.pb.h"
#include <functional>
using namespace std::placeholders;
using namespace rpc;
static const std::string NormalService_method_names[] = {
    "NormalService.GetTime"};
class NormalService : public RpcService {
public:
  virtual Status GetTime(GetTimeReq *request, GetTimeResp *response) = 0;
  NormalService();
  ~NormalService();
};
